"""add new columns to paper

Revision ID: 118264f64659
Revises: f22699bcfb4c
Create Date: 2024-10-27 17:33:29.666606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118264f64659'
down_revision = 'f22699bcfb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('payment_path')
        batch_op.drop_column('payment_confirmed')
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
