"""add review questions

Revision ID: 2af81ef8c6d1
Revises: 89660a096e3a
Create Date: 2024-11-05 16:20:27.717461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2af81ef8c6d1'
down_revision = '89660a096e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('paper_status',
               existing_type=mysql.ENUM('A', 'R', 'P', 'AMAR', 'AMIR', 'CUR', 'RF'),
               nullable=False)

    with op.batch_alter_table('review_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_questions', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('A', 'R', 'P', 'AMAR', 'AMIR', 'CUR', 'RF'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_history', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('A', 'R', 'P', 'AMAR', 'AMIR', 'CUR', 'RF'),
               nullable=True)
        batch_op.drop_column('review_questions')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('paper_status',
               existing_type=mysql.ENUM('A', 'R', 'P', 'AMAR', 'AMIR', 'CUR', 'RF'),
               nullable=True)

    # ### end Alembic commands ###
