"""update

Revision ID: 708409153adb
Revises: 2af81ef8c6d1
Create Date: 2024-11-06 10:09:01.751427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '708409153adb'
down_revision = '2af81ef8c6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.alter_column('paper_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('reviewer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.alter_column('reviewer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('paper_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
