"""user update abstract

Revision ID: 80df780aa5ed
Revises: 252659125515
Create Date: 2024-10-23 22:15:44.067093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80df780aa5ed'
down_revision = '252659125515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=mysql.VARCHAR(length=350),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('abstract',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=350),
               existing_nullable=True)

    # ### end Alembic commands ###
