"""update model

Revision ID: 9fd2e0348110
Revises: ce464c8d5bad
Create Date: 2024-10-31 02:28:56.802524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fd2e0348110'
down_revision = 'ce464c8d5bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('A', 'R', 'P', 'AMAR', 'AMIR', name='paperstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('A', 'R', 'P', 'AMAR', 'AMIR', name='paperstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_reviewer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_reviewer_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_theme', sa.String(length=255), nullable=True))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'ATTENDEE', 'REVIEWER', 'AUTHOR', 'EDITOR'),
               type_=sa.Enum('AUTHOR', 'REVIEWER', 'EDITOR', 'ATTENDEE', 'ADMIN', name='role'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('AUTHOR', 'REVIEWER', 'EDITOR', 'ATTENDEE', 'ADMIN', name='role'),
               type_=mysql.ENUM('ADMIN', 'ATTENDEE', 'REVIEWER', 'AUTHOR', 'EDITOR'),
               nullable=True)
        batch_op.drop_column('assigned_theme')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_reviewer_id')

    op.drop_table('reviews')
    op.drop_table('review_history')
    # ### end Alembic commands ###
