"""update model

Revision ID: a67d75f42165
Revises: ce2d8398a353
Create Date: 2024-10-31 21:40:05.515293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67d75f42165'
down_revision = 'ce2d8398a353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_paper_reviewer', ['paper_id', 'reviewer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_history', schema=None) as batch_op:
        batch_op.drop_constraint('uix_paper_reviewer', type_='unique')

    # ### end Alembic commands ###
