"""update model

Revision ID: daa880a820ed
Revises: 80df780aa5ed
Create Date: 2024-10-25 16:24:53.797278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa880a820ed'
down_revision = '80df780aa5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_status', sa.Enum('A', 'R', 'P', 'AMAR', 'AMIR', name='paperstatus'), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('payment_path')
        batch_op.drop_column('payment_confirmed')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('paper_status')

    # ### end Alembic commands ###
