"""update

Revision ID: e741b023a878
Revises: a67d75f42165
Create Date: 2024-11-02 12:51:59.944002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e741b023a878'
down_revision = 'a67d75f42165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_history', schema=None) as batch_op:
        batch_op.alter_column('paper_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('reviewer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_history', schema=None) as batch_op:
        batch_op.alter_column('reviewer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('paper_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
