"""paper update

Revision ID: f3a31c24aa55
Revises: 9fd2e0348110
Create Date: 2024-10-31 19:47:28.518471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3a31c24aa55'
down_revision = '9fd2e0348110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_comment', sa.Text(), nullable=True))
        batch_op.alter_column('paper_status',
               existing_type=mysql.ENUM('A', 'R', 'P', 'AMAR', 'AMIR', 'CUR'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.alter_column('paper_status',
               existing_type=mysql.ENUM('A', 'R', 'P', 'AMAR', 'AMIR', 'CUR'),
               nullable=True)
        batch_op.drop_column('review_comment')

    # ### end Alembic commands ###
